dbPass: ENC[AES256_GCM,data:BYxYzXuvUQfcoUg=,iv:Qp/afF6ZcgvN4riqfFWSuuOVfx2310vO6aUZVrLRYdA=,tag:G50Ydxe/4+hjL6uezvKTYQ==,type:str]
karpoUserSecret: ENC[AES256_GCM,data:ipTiBN1uGY5dnEeG5kajd3fjRR4=,iv:NP6cYxB7mVUPAW+IMtjI8AhV0bfVf2y66ov56QayTr0=,tag:zSz3KOo6ZLxj0JIH7D6ijA==,type:str]
grafanaPass: ENC[AES256_GCM,data:qkLuXtlEsiTeOWk=,iv:VwM36PD1qDWoT6M6Pb5OavJI1fBT3OC8C1x7mNj35vE=,tag:a9sY8pkIR0dz3Sw1qZyp8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wk9c95a5m5dgcecw73lr7v4086dcspgzwzg84msjdk4wxkpd2daq2uqtm4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWGdtNklFNnpWQ09TU0No
            bzB1cHIvSHljY3pXOW9mZWdLTTdQMS9IMDJRCjRGbW5PZjIxV3pOMzNHVHJYVmhi
            Y1QwOFBJeGNlWFFTTHdXZlBGd1F4YlEKLS0tIHlQY3dsR3ZXK1d2ZDd0bTd2Z3hm
            SmljUE9Ec1IzczNyQmxkSFhJRmoxdm8KXQueJb3/Wd/d4MFc2GvlRZoPYbUF3l89
            4vCV3NLdFMWLmDjU85LaYXS9/PNAGzBtEYnBOOzmjklnDHNPOwKGxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-15T13:38:07Z"
    mac: ENC[AES256_GCM,data:GCTR5+QtMp8BdxDbR0326yUjlplAWNXxuKzY2vYhgs/DgIhRH1UikcqfknFnL9bBEamN4xV68yhDzZnYfQKBryjfbNBViAhOW0twte1vEGZuPUZwVRihDPGkfTj/JYyLv9vd2UoRyHh5xixmZ5AFz3TMKDcrCevYWzhL+z6i7Xs=,iv:7Pj+FyFp3OmyQfrwjUqcasEfhcO/m7bp9P9fBkhWnUw=,tag:dcq6HNfMWgizWchYkcW6FA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
