apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "karpo_backend.fullname" . }}
spec:
  selector:
    matchLabels:
      {{- include "karpo_backend.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: /metrics
  namespaceSelector:
    any: true